name: Python Scheduled Script

on:
  schedule:
    - cron: "00 12 * * *"
      timezone: "Europe/Athens"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v6 # Checkout the repository content to github runner.
      - name: Setup Python Version
        uses: actions/setup-python@v3
        with:
          python-version: 3.9 # Install the python version needed

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3
        with:
          path: "requirements.txt"
      - name: Execute Python script
        run: python x.py

      - name: Commit files
        run:
          git config --local user.name lelios1
          git config --local user.email "thelelios1@gmail.com"
          git add --all
          git commit -am "GH ACTION Headlines $(date)"
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
